description: ${DESC}
tasks:
  - name: training
    spec:
      image: ${IMAGE_NAME}
      resultPath: /output
      args:
        - python
        - scripts/run_experiment.py
        - --model_type
        - ${MODEL_TYPE}
        - --model_name_or_path
        - ${MODEL_NAME_OR_PATH}
        - --task_name
        - ${TASK_NAME}
        - --do_eval
        - --do_lower_case
        - --data_dir
        - ${DATA_DIR}
        - --max_seq_length
        - ${MAX_SEQ_LENGTH}
        - --per_gpu_eval_batch_size
        - ${EVAL_BATCH_SIZE}
        - --per_gpu_train_batch_size
        - ${TRAIN_BATCH_SIZE}
        - --learning_rate
        - ${LEARNING_RATE}
        - --num_train_epochs
        - ${NUM_EPOCHS}
        - --output_dir
        - ${OUTPUT_DIR}
        - --do_train
        - --logging_steps
        - ${LOGGING_STEPS}
        - --save_steps
        - ${SAVE_STEPS}
        - --seed
        - ${SEED}
        - --data_cache_dir
        - /output/cache/
        - --warmup_pct
        - ${WARMUP_PCT}
        - --evaluate_during_training
      env:
        MODEL_TYPE: ${MODEL_TYPE}
        MODEL_NAME_OR_PATH: ${MODEL_NAME_OR_PATH}
        TASK_NAME: ${TASK_NAME}
        DATA_DIR: ${DATA_DIR}
        MAX_SEQ_LENGTH: ${MAX_SEQ_LENGTH}
        EVAL_BATCH_SIZE: ${EVAL_BATCH_SIZE}
        TRAIN_BATCH_SIZE: ${TRAIN_BATCH_SIZE}
        LEARNING_RATE: ${LEARNING_RATE}
        NUM_EPOCHS: ${NUM_EPOCHS}
        SEED: ${SEED}
      datasetMounts:
        - datasetId: ${WINOGRANDE_DATASET}
          containerPath: ${MOUNT_POINT}
      requirements:
        gpuCount: ${GPU_COUNT}
        gpuType: v100
        preemptible: true
